import 'dart:async';
import 'dart:ui';
import 'package:assets_audio_player/assets_audio_player.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:geolocator/geolocator.dart';
import 'package:saglik_kapimda/models/driver_data.dart';
import 'package:saglik_kapimda/models/user_model.dart';

final FirebaseAuth fAuth= FirebaseAuth.instance;
User currentFirebaseUser;
UserModel userModelCurrentInfo;
StreamSubscription<Position> streamSubscriptionPosition;
StreamSubscription<Position> streamSubscriptionDriverLivePosition;
AssetsAudioPlayer audioPlayer = AssetsAudioPlayer();
Position  driverCurrentPosition;
DriverData onlineDriverData = DriverData();
String driverVehicleType = "";
String titleStarsRating ="İyi";
bool isDriverActive = false;
String statusText = "Çevrimdışı";
Color  buttonColor = Colors.deepPurpleAccent;